[package]
name = "mfp-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Background player daemon for musicforprogramming.net"

[dependencies]
mfp-core.workspace = true

anyhow.workspace = true
libc.workspace = true
reqwest.workspace = true
rodio.workspace = true
rustfft.workspace = true
serde.workspace = true
serde_json.workspace = true
stream-download.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
